FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY . .
RUN npm ci --fetch-retries=5 --fetch-retry-mintimeout=2000 --fetch-retry-maxtimeout=30000
RUN npx turbo run build --filter=@wr/webapp

FROM nginx:1.27-alpine AS runtime
COPY docker/nginx-webapp.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/webapp/dist /usr/share/nginx/html
EXPOSE 8080
