import fs from 'node:fs';
import path from 'node:path';
import JSZip from 'jszip';

const root=process.cwd();
const input=path.join(root,'docs','Report','Template2_RDS Document.docx');
const output=path.join(root,'docs','Report','Bao_Cao_RDS_RMS_Phan_III_IV_Hoan_Thien.docx');
const esc=(s='')=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

const p=(text,{level=0,bold=false,italic=false,center=false,breakBefore=false,keep=false,size=null,color=null}={})=>{
  const sizes={0:22,1:32,2:28,3:24,4:22}; const sz=size||sizes[level]||22;
  const before=level===1?320:level===2?240:level===3?180:40;
  const after=level?120:100;
  const num=level?`<w:outlineLvl w:val="${Math.min(level-1,8)}"/>`:'';
  return `<w:p><w:pPr>${breakBefore?'<w:pageBreakBefore/>':''}${keep||level?'<w:keepNext/>':''}<w:spacing w:before="${before}" w:after="${after}" w:line="276" w:lineRule="auto"/>${center?'<w:jc w:val="center"/>':''}${num}</w:pPr><w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="${sz}"/>${bold||level?'<w:b/>':''}${italic?'<w:i/>':''}${color?`<w:color w:val="${color}"/>`:''}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`;
};
const bullet=(text)=>`<w:p><w:pPr><w:ind w:left="540" w:hanging="270"/><w:spacing w:after="70" w:line="276" w:lineRule="auto"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="22"/></w:rPr><w:t xml:space="preserve">• ${esc(text)}</w:t></w:r></w:p>`;
const cell=(text,width,{head=false,center=false}={})=>`<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/><w:tcMar><w:top w:w="90" w:type="dxa"/><w:left w:w="110" w:type="dxa"/><w:bottom w:w="90" w:type="dxa"/><w:right w:w="110" w:type="dxa"/></w:tcMar>${head?'<w:shd w:fill="D9EAF7"/>':''}<w:vAlign w:val="center"/></w:tcPr><w:p><w:pPr><w:spacing w:after="20" w:line="240" w:lineRule="auto"/>${center?'<w:jc w:val="center"/>':''}</w:pPr><w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/><w:sz w:val="19"/>${head?'<w:b/>':''}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p></w:tc>`;
const table=(headers,rows,widths)=>`<w:tbl><w:tblPr><w:tblW w:w="${widths.reduce((a,b)=>a+b,0)}" w:type="dxa"/><w:tblInd w:w="0" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="6" w:color="7F7F7F"/><w:left w:val="single" w:sz="6" w:color="7F7F7F"/><w:bottom w:val="single" w:sz="6" w:color="7F7F7F"/><w:right w:val="single" w:sz="6" w:color="7F7F7F"/><w:insideH w:val="single" w:sz="4" w:color="BFBFBF"/><w:insideV w:val="single" w:sz="4" w:color="BFBFBF"/></w:tblBorders></w:tblPr><w:tblGrid>${widths.map(w=>`<w:gridCol w:w="${w}"/>`).join('')}</w:tblGrid><w:tr><w:trPr><w:tblHeader/></w:trPr>${headers.map((h,i)=>cell(h,widths[i],{head:true,center:true})).join('')}</w:tr>${rows.map(r=>`<w:tr>${r.map((v,i)=>cell(v,widths[i],{center:i===0||i===1})).join('')}</w:tr>`).join('')}</w:tbl>${p('')}`;

const modules=[
 {title:'1. System Architecture and Shared Platform', sub:'1.1 High-Level Runtime Design', ucs:'UC-60, UC-61 and all cross-cutting use cases', desc:'RMS is a TypeScript monorepo. React/Vite communicates with the NestJS HTTP Gateway. The Gateway validates JWT and roles, then calls Identity, Recruiting, Profiles/CV, Interview and Notification services. PostgreSQL is shared through Prisma; Redis/BullMQ handles asynchronous CV parsing, embeddings and reminders.', fields:[['Web application','React 19 SPA','Role-specific routes, forms, dashboards and reusable UI components.'],['API Gateway','NestJS HTTP','REST endpoint, Swagger, validation, JWT/role guard and TCP proxy.'],['Domain services','NestJS microservices','Identity, Recruiting, Profiles/CV, Interview and Notification business logic.'],['Worker','BullMQ consumer','Processes CV extraction, embedding and deadline notification jobs.'],['Data platform','PostgreSQL + pgvector','Transactional RMS data and 384-dimensional vector search.'],['Queue/cache','Redis 7','BullMQ transport, retry control and asynchronous processing.']], db:[['All domain tables','CRUD','Accessed through service-owned Prisma repositories; the Gateway does not query the database directly.'],['AuditLog / RequestLog','C,R','Records actor, transition, entity and timestamp for traceability.'],['Redis queues','C,R,U,D','Stores pending, active, completed and failed background jobs with retry policies.']], impl:'Key paths: services/gateway, services/identity, services/recruiting, services/profiles, services/cv, services/interview, services/notification, services/worker, packages/contracts, packages/database, packages/queue and packages/ai.'},
 {title:'2. Authentication, Identity and Administration', sub:'2.1 Login, Profile, User and Organization Management', ucs:'UC-01 to UC-15, UC-60', desc:'Provides registration, OTP verification, login, refresh-token rotation, logout, password recovery, profile management, user/role/status administration, organizations, departments and Google Calendar connection. The frontend redirects users to the dashboard permitted by their canonical role.', fields:[['Email','Text box','Required login/registration identifier; normalized and checked for uniqueness.'],['Password','Password box','Validated client-side and server-side; stored only as a password hash.'],['OTP','Numeric/text input','Short-lived registration or reset verification code.'],['Role','Select','ADMIN, HR_MANAGER/HR, DEPARTMENT_HEAD or CANDIDATE according to canonical contracts.'],['Account status','Switch/select','Activates or deactivates internal accounts.'],['Organization / Department','Select','Scopes user access, reporting and recruitment ownership.'],['Google Calendar','Connect action','Starts OAuth and stores refresh token for authorized scheduling.']], db:[['User','C,R,U,D','Account, role, status, profile summary and Google Calendar refresh token.'],['Organization','C,R,U','Company-level configuration and settings.'],['Department','C,R,U,D','Department structure and department-head ownership.'],['AuditLog','C,R','Records administrative account and role changes.']], impl:'Representative APIs: /api/v1/auth/*, /api/v1/me/profile, /api/v1/users, /api/v1/organizations, /api/v1/departments, /api/v1/google-calendar/auth-url and /api/v1/oauth2callback.'},
 {title:'3. Recruitment Request and Approval Workflow', sub:'3.1 Request Creation, Review, Approval and Timeline', ucs:'UC-16 to UC-23', desc:'Department Heads create recruitment requests, save drafts and submit them to HR. HR validates business need, assigns recruiters, requests revision or forwards to Admin. Admin makes the final approval/rejection decision. Every transition is state-validated and written to the request log.', fields:[['Position title','Text box','Required role/position requested by the department.'],['Headcount','Number','Positive requested hiring quantity.'],['Job description','Rich text/textarea','Responsibilities, skills, qualification and business justification.'],['Urgency / dates','Select/date','Priority and expected recruitment period.'],['Assignee','User select','Eligible active HR member responsible for handling the request.'],['Decision / reason','Action + textarea','Approve, reject, request changes or return for revision with mandatory reason where applicable.'],['Timeline','Read-only list','Displays RequestLog entries in chronological order.']], db:[['RecruitmentRequest','C,R,U,D','Stores request content, owner, assignee, lifecycle state and filled count.'],['ApprovalRecord','C,R','Stores formal review/approval decisions.'],['RequestLog','C,R','Immutable workflow transition and note history.'],['Department / User','R','Resolves department scope, requester and HR assignee.']], impl:'Representative APIs: GET/POST/PATCH /api/v1/recruitment-requests, submit, assign, return-for-revision, request-changes, forward-to-admin and decision endpoints.'},
 {title:'4. Recruitment Planning, Tasks and Campaigns', sub:'4.1 Overall Plan and Task Plan Workspace', ucs:'UC-24 to UC-31', desc:'An approved recruitment request is converted into an OverallPlan. HR defines dates, activities and TaskPlans, submits the plan for Admin approval and starts the campaign only after approval. Task assignment, progress and deadline reminders provide operational control.', fields:[['Plan period','Date range','Start/end dates must be valid and cover child task dates.'],['Plan status','Status badge','Draft, pending approval, approved/active, rejected or revision state.'],['Task type','Select','Operational recruitment activity such as sourcing, screening or interview coordination.'],['Assignee','HR user select','Active eligible recruiter responsible for the task.'],['Deadline','Date/time','Used by worker reminder jobs and overdue tracking.'],['Task status','Status control','PENDING, IN_PROGRESS or COMPLETED with guarded transitions.'],['Revision note','Textarea','Required when Admin rejects or requests changes.']], db:[['OverallPlan','C,R,U','Plan scope, dates, status, approval and campaign start data.'],['TaskPlan','C,R,U','Task type, assignee, deadline, status and notes.'],['TaskReminder','C,R,U','Deduplicated reminder schedule and delivery state.'],['Notification / EmailLog','C,R,U','Reminder messages and delivery records.']], impl:'Representative APIs: /api/v1/overall-plan, submit, approve, reject, resubmit, start-campaign; /api/v1/task-plan and task status/assignment endpoints.'},
 {title:'5. Candidate, CV, Applications and Talent Search', sub:'5.1 Candidate Profile, CV Processing and Hybrid Search', ucs:'UC-32 to UC-42', desc:'Candidates maintain profiles, upload CVs and apply to published jobs. CV files are stored with metadata, parsed asynchronously and converted into 384-dimensional embeddings. HR searches the Talent Pool using semantic similarity combined with graph/coverage signals and can submit search feedback.', fields:[['Profile fields','Form controls','Name, contact, skills, experience, education and availability.'],['CV file','File upload','PDF/DOC/DOCX with type/size validation and processing state.'],['Job posting','Card/detail','Published role, requirements, status and apply action.'],['Search query','Text input','Free-text requirements expanded before embedding/search.'],['Filters','Selects','Department, skills, experience, location and availability.'],['Ranked result','Result card/table','Candidate, similarity, supporting skill/coverage evidence and latest CV.'],['Feedback','Relevant/not relevant action','Stores search quality signal and training triplets.']], db:[['CandidateProfile','C,R,U','Candidate identity-linked profile and structured attributes.'],['CandidateCV','C,R,U,D','File metadata, raw/parsed content and processing status.'],['CvEmbedding','C,R,U,D','384-dimensional pgvector representation linked to CV.'],['JobPosting','C,R,U','Recruitment advertising lifecycle and media.'],['Application','C,R,U','Candidate application and screening status.'],['TalentSearchRun / TalentSearchFeedback','C,R','Search trace, ranking evidence and feedback.']], impl:'Upload writes CV metadata first; BullMQ workers parse and embed asynchronously. Search uses packages/ai plus pgvector. Representative APIs: /api/v1/cv, /candidate-profiles, /applications, /job-postings, /cv/search, /talent/search and /talent/feedback.'},
 {title:'6. Interview Scheduling, Calendar and Evaluation', sub:'6.1 Online/Offline Interview Coordination and Results', ucs:'UC-43 to UC-53', desc:'HR schedules interviews for candidates under an approved plan, selects at least two active internal panel members, chooses online or offline mode, sends invitations and manages reschedule/cancel/confirmation. Online mode may create Google Meet; offline mode records venue and supporting evidence. Panel feedback and final recommendation are stored separately for Admin review.', fields:[['Candidate / request','Search/select','Selects an eligible application and recruitment request.'],['Interview mode','Radio/select','ONLINE or OFFLINE; controls link versus venue/evidence requirements.'],['Date and time','Date/time picker','Must be future-valid and checked for panel conflicts.'],['Panel','Multi-select','At least two distinct active internal interviewers.'],['Meeting link / venue','Text','Meet URL for online mode or physical location for offline mode.'],['Offline evidence','Upload/reference','Proof available to Admin during result review.'],['Scores','Numeric controls','Technical, communication and culture scores.'],['Decision and notes','Select/textarea','Individual decision, evaluator notes, summary and final recommendation.']], db:[['InterviewSchedule','C,R,U','Time, mode, location/link, panel, status and calendar reference.'],['InterviewResult','C,R,U','Per-evaluator feedback, scores, decision and final recommendation.'],['EmailLog','C,R','Invitation/reminder delivery history.'],['Notification','C,R,U','Candidate and panel in-app updates.'],['User','R,U','Panel eligibility and Google Calendar refresh token.']], impl:'Google Meet creation uses conferenceDataVersion=1. Invitations use sendUpdates=all. Representative APIs: /api/v1/interviews/schedules, reschedule, cancel, confirm, invitations, details, my-feedback, results, HR interview results and Admin interview results.'},
 {title:'7. Hiring Decision, Offers and Notifications', sub:'7.1 Decision-to-Offer and Candidate Response', ucs:'UC-54 to UC-57', desc:'Admin reviews interview results and chooses HIRE, REJECT or requests more information. A HIRE decision requires compensation and start date and creates an offer transactionally. HR reviews/sends the offer; the owning candidate accepts or declines. Notifications and EmailLog records preserve communication history.', fields:[['Decision','Select/action','HIRE, REJECT or REQUEST_INFO according to permitted workflow state.'],['Compensation','Currency/number','Required for HIRE and validated as a positive amount.'],['Start date','Date','Required for HIRE and must satisfy business constraints.'],['Reason / request note','Textarea','Required for reject or request-more-information paths.'],['Offer preview','Read-only document view','Candidate, role, compensation, start date and terms.'],['Candidate response','Accept/Decline action','Ownership-scoped response with optional note.'],['Notification center','List/actions','Read, unread, delete and mark-all-read operations with SSE updates.']], db:[['OfferLetter','C,R,U','Offer content, send state, response, note and timestamps.'],['RecruitmentRequest / Application','R,U','Updates final workflow and candidate outcome.'],['Notification','C,R,U,D','User-scoped in-app messages and read state.'],['EmailLog','C,R','Outbound email template, status, error and related entity.'],['AuditLog / RequestLog','C,R','Final decision and workflow evidence.']], impl:'Representative APIs: /api/v1/hiring-decisions/:requestId, request-info, /api/v1/offers, offer send/respond and /api/v1/notifications including SSE.'},
 {title:'8. Dashboards, Reports, Security and Operations', sub:'8.1 Role Dashboards, Analytics and Health Monitoring', ucs:'UC-58 to UC-61', desc:'Each role receives a scoped dashboard. Admin sees approval queues and strategic metrics; HR sees requests, campaigns, tasks and interviews; Department Heads see their department; Candidates see applications, interviews and offers. Report services calculate annual, department, time-to-hire, pipeline and realtime tracking data.', fields:[['Role dashboard','Cards/tables','Scoped counts, pending actions and navigation shortcuts.'],['Date/year filters','Date/select','Controls annual, department and pipeline aggregation.'],['Department filter','Select','Restricted by actor scope where required.'],['Export','Button','Downloads supported annual report output.'],['Realtime tracking','Table','Request owner, pending action, task/interview/offer counters and update time.'],['Health status','Status response','Gateway and dependent service availability.'],['Audit lookup','Filter/table','Entity type/id search over audit history.']], db:[['RecruitmentRequest / RequestLog','R','Pipeline, annual, ownership and time-to-hire metrics.'],['OverallPlan / TaskPlan','R','Campaign and work-progress metrics.'],['InterviewSchedule / InterviewResult','R','Interview workload and outcome metrics.'],['OfferLetter / Application','R','Offer and candidate conversion metrics.'],['AuditLog','R','Operational traceability.']], impl:'Representative APIs: /api/v1/reports/admin-dashboard, annual, departments, department/:id, time-to-hire, pipeline, annual/export, realtime-tracking, /api/v1/audit-logs and /api/v1/health.'}
];

let content=p('III. Design Specifications',{level:1,bold:true,breakBefore:true});
content+=p('This section translates the RMS requirement specifications into implementable screen, service, database and integration designs. UI labels may be refined during usability review, but access scope, workflow transitions and data ownership are mandatory.',{italic:true});
for(const m of modules){
 content+=p(m.title,{level:2}); content+=p(m.sub,{level:3});
 content+=p('a. Screen / Function Description',{level:4}); content+=p(m.desc); content+=p(`Related use cases: ${m.ucs}`,{italic:true});
 content+=p('UI Design and Components',{level:4}); content+=table(['Field / Component','Field Type','Description'],m.fields,[2100,1800,5460]);
 content+=p('Database Access',{level:4}); content+=table(['Table / Store','CRUD','Description'],m.db,[2350,900,6110]);
 content+=p('API / Implementation Design',{level:4}); content+=p(m.impl);
 content+=p('Data-access rule: all mutations are validated and authorized before Prisma/queue operations. Queries are parameterized through Prisma or safe pgvector helpers; passwords, tokens and secrets are never embedded in SQL or returned in API payloads.');
}

content+=p('IV. Appendix',{level:1,bold:true,breakBefore:true});
content+=p('1. Assumptions & Dependencies',{level:2});
const assumptions=[
['AS-01','All users have a unique email address and a valid canonical RMS role.'],['AS-02','Internal users belong to an organization and, where applicable, a department.'],['AS-03','Department Heads provide complete recruitment justification and job requirements before submission.'],['AS-04','HR and Admin follow the configured workflow rather than modifying database state directly.'],['AS-05','Uploaded CVs are readable PDF, DOC or DOCX files within configured limits.'],['AS-06','Interview panel members maintain accurate availability and contact information.'],['AS-07','Server time, database time and business timezone are synchronized.'],['AS-08','Email addresses and Google accounts used for calendar invitations are reachable.'],['AS-09','Report accuracy depends on complete RequestLog, interview, application and offer events.'],['AS-10','The system is deployed for a single enterprise organization in the MVP unless organization scoping is explicitly enabled.']
];
const deps=[
['DE-01','Node.js 22+, npm workspaces and Turborepo for build orchestration.'],['DE-02','PostgreSQL 16 with pgvector enabled and Prisma migrations applied.'],['DE-03','Redis 7 and BullMQ workers for CV, embedding and reminder jobs.'],['DE-04','Object/file storage configuration for CV, avatar, evidence and job-posting media.'],['DE-05','SMTP/email provider configuration for OTP, invitations, reminders, offers and rejections.'],['DE-06','Google OAuth credentials and Calendar API for optional Google Meet/calendar integration.'],['DE-07','Supabase configuration when Supabase-backed login/registration is enabled.'],['DE-08','Local ONNX embedding model or configured embedding endpoint producing 384 dimensions.'],['DE-09','Gemini configuration when Gemini-based CV extraction is selected.'],['DE-10','Modern browser with JavaScript, secure cookies/local session storage and SSE support.']
];
content+=table(['ID','Assumption'],assumptions,[1200,8160]); content+=table(['ID','Dependency'],deps,[1200,8160]);

content+=p('2. Limitations & Exclusions',{level:2});
const limits=[
['LE-01','RMS supports recruitment workflow management; it is not a payroll, attendance or employee-performance system.'],['LE-02','AI assists CV extraction and search; it does not make autonomous hiring decisions.'],['LE-03','Semantic ranking quality depends on parsed CV content and successful embedding generation. Newly uploaded CVs may not be searchable until asynchronous jobs finish.'],['LE-04','Google Calendar reminders do not guarantee email delivery; strict delivery requires the RMS notification/email worker.'],['LE-05','Calendar conflict detection is limited to accessible calendars and information granted by users.'],['LE-06','Offline interview evidence is retained for review but is not a digital-signature or legal-verification service.'],['LE-07','The MVP uses a shared PostgreSQL database; independent database-per-service deployment is excluded.'],['LE-08','Annual export supports implemented CSV/PDF formats only; arbitrary report-builder functionality is excluded.'],['LE-09','Mobile native applications are excluded; responsive web access is the supported client.'],['LE-10','External job boards, HRIS, payroll and background-check integrations are excluded unless separately configured.'],['LE-11','The system does not guarantee extraction accuracy for encrypted, scanned or malformed CV documents.'],['LE-12','Disaster recovery, multi-region active-active deployment and unlimited retention are operational extensions beyond the MVP.']
];
content+=table(['ID','Limitation / Exclusion'],limits,[1200,8160]);

content+=p('3. Business Rules',{level:2});
const rules=[
['BR-01','Security','Every protected API requires a valid access token and an authorized role.'],['BR-02','Identity','Inactive users cannot authenticate or perform protected business actions.'],['BR-03','Scope','Users may access only organization, department, request, candidate or offer records permitted by their role and ownership.'],['BR-04','Request workflow','A recruitment request must follow valid state transitions; rejection, revision and request-change actions require a reason.'],['BR-05','Approval','Only Admin performs final request approval and final hiring decision.'],['BR-06','Plan lock','Sourcing, screening, interview and offer activities are blocked until the related OverallPlan is approved/active.'],['BR-07','Task planning','Task dates must be within the OverallPlan period; only eligible active HR users may be assigned.'],['BR-08','CV processing','A CV becomes semantically searchable only after parse success and creation of a 384-dimensional embedding.'],['BR-09','Search','Hybrid ranking may combine vector similarity, skill-graph proximity and requirement coverage; ranking is advisory.'],['BR-10','Interview panel','A scheduled interview requires at least two distinct active internal panel members.'],['BR-11','Interview mode','ONLINE requires a meeting link or successfully generated Meet link; OFFLINE requires a venue and may require supporting evidence for Admin review.'],['BR-12','Calendar','Meet creation uses authorized Google Calendar credentials; attendee updates are sent to configured participants.'],['BR-13','Feedback','Only authorized panel/HR evaluators may submit feedback; an evaluator cannot impersonate another evaluator.'],['BR-14','Decision','HIRE requires candidateId, compensation and startDate; REJECT or REQUEST_INFO requires an explanatory reason/note.'],['BR-15','Offer ownership','Only the candidate who owns an offer may accept or decline it; a finalized response cannot be silently overwritten.'],['BR-16','Notifications','Notifications are user-scoped; only the owner may read, mark, delete or stream them.'],['BR-17','Audit','Material workflow, role, decision and status changes must write RequestLog and/or AuditLog records.'],['BR-18','Reminders','Deadline reminders must be idempotent and must not create duplicate notification/email logs for the same reminder point.'],['BR-19','Reporting','Department Heads see their department only; HR and Admin report scope follows configured role permissions.'],['BR-20','Data integrity','Database mutations that create related decision, offer, log and notification records must be transactional where consistency requires it.']
];
content+=table(['ID','Category','Rule Definition'],rules,[1050,1650,6660]);

content+=p('4. Traceability and Technical References',{level:2});
const refs=[
['Functional requirements','docs/use-case-specifications.md; docs/backend-endpoints-summary.md; docs/all-tasks.md'],['Architecture','docs/architecture.md; docs/project-overview.md; docs/source-tree-analysis.md'],['Database','packages/database/prisma/schema.prisma; packages/database/prisma/migrations'],['API Gateway','services/gateway/src/controllers'],['Domain services','services/identity; services/recruiting; services/profiles; services/cv; services/interview; services/notification'],['Frontend','webapp/src/features; webapp/src/App.tsx; webapp/src/metadata.json'],['AI and workers','packages/ai; packages/ai-models; services/worker; packages/queue'],['Contracts and validation','packages/contracts; packages/config']
];
content+=table(['Area','Repository Reference'],refs,[2450,6910]);
content+=p('Document completion note: Sections III and IV are grounded in the current RMS repository structure and implemented endpoints as of 11 July 2026. If database models, role enums, APIs or workflow states change, these sections must be updated in the same change set.',{italic:true});

const zip=await JSZip.loadAsync(fs.readFileSync(input));
let xml=await zip.file('word/document.xml').async('string');
const ps=[...xml.matchAll(/<w:p(?:\s[^>]*)?>[\s\S]*?<\/w:p>/g)];
const texts=ps.map(m=>[...m[0].matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>/g)].map(q=>q[1]).join(''));
const start=texts.findIndex((t,i)=>i>115&&t.includes('III. Design Specifications'));
if(start<0) throw new Error('Could not locate body Section III in template');
const startAt=ps[start].index;
const sectAt=xml.lastIndexOf('<w:sectPr');
if(sectAt<startAt) throw new Error('Could not locate final section properties');
xml=xml.slice(0,startAt)+content+xml.slice(sectAt);
zip.file('word/document.xml',xml);
if(zip.file('word/settings.xml')){
 let settings=await zip.file('word/settings.xml').async('string');
 if(!settings.includes('<w:updateFields')) settings=settings.replace('</w:settings>','<w:updateFields w:val="true"/></w:settings>');
 zip.file('word/settings.xml',settings);
}
const bytes=await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE'});
fs.writeFileSync(output,bytes);
console.log(JSON.stringify({input,output,modules:modules.length,assumptions:assumptions.length,dependencies:deps.length,limitations:limits.length,businessRules:rules.length,bytes:bytes.length},null,2));
